---

- name: create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: download googlechrome apt key
  get_url:
    url: "{{ googlechrome_apt_key }}"
    dest: /etc/apt/keyrings/googlechrome.asc
    mode: '0644'

- name: add google chrome repo
  apt_repository:
    repo: "{{ googlechrome_repo }}"
    state: present
    filename: google-chrome

- name: install latest google chrome
  apt:
    name: google-chrome-stable
    force_apt_get: yes

...
