---

- name: install security packages
  apt:
    name: "{{ security_packages }}"
    state: present
    force_apt_get: yes

- name: install vpn packages
  apt:
    name: "{{ security_vpn_packages }}"
    state: present
    force_apt_get: yes

...