---

- name: create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: download vscode apt key
  get_url:
    url: "{{ vscode_apt_key }}"
    dest: /etc/apt/keyrings/vscode.asc
    mode: '0644'

- name: add vscode repo
  apt_repository:
    repo: "{{ vscode_repo }}"
    state: present
    filename: vscode

- name: install latest visual studio code
  apt:
    name: code
    force_apt_get: yes

- name: install some popular vscode extensions
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ local_username }}"

...
