---

hashicorp_repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ upstream_release.stdout }} main"    # ubuntu 20.04 LTS
hashicorp_apt_key: "https://apt.releases.hashicorp.com/gpg"

hashicorp_packages:
  - vagrant
  - terraform
  - packer

...
