---

security_packages:
  - clamav
  - clamtk-gnome    # right click clamav scan access from nautilus
  - clamav-daemon  # for real time scanning; not installed in case it impacts performance

security_vpn_packages:
  - wireguard
  - openvpn

tailscale_apt_key: "https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg"
tailscale_apt_repo: "https://pkgs.tailscale.com/stable/ubuntu"

...
