---

- name: add hashicorp apt key
  apt_key:
    url: "{{ hashicorp_apt_key }}"

- name: add hashicorp repo
  apt_repository:
    repo: "{{ hashicorp_repo }}"
    state: present
    filename: hashicorp

- name: install hashicorp packages
  apt:
    name: "{{ hashicorp_packages }}"
    force_apt_get: yes

...
