---

- name: create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# kubectl
- name: download kubernetes apt key
  get_url:
    url: "{{ kubernetes_apt_key }}"
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: '0644'

- name: add kubernetes apt repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes.asc] {{ kubernetes_apt_repo }} /"
    state: present
    filename: kubernetes

- name: install kubectl
  apt:
    name: kubectl
    state: present
    update_cache: yes
    force_apt_get: yes

# helm
- name: install helm via official script
  shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

# k9s
- name: install k9s binary
  shell: |
    curl -fsSL https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz | tar xz -C /usr/local/bin k9s
  args:
    creates: /usr/local/bin/k9s

...
