---

- name: create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# kubectl
- name: download kubernetes apt key
  get_url:
    url: "{{ kubernetes_apt_key }}"
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: '0644'

- name: add kubernetes apt repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes.asc] {{ kubernetes_apt_repo }} /"
    state: present
    filename: kubernetes

- name: install kubectl
  apt:
    name: kubectl
    state: present
    update_cache: yes
    force_apt_get: yes

# helm
- name: download and dearmor helm apt key
  shell: curl -fsSL "{{ helm_apt_key }}" | gpg --dearmor -o /etc/apt/keyrings/helm.gpg
  args:
    creates: /etc/apt/keyrings/helm.gpg

- name: set helm apt key permissions
  file:
    path: /etc/apt/keyrings/helm.gpg
    mode: '0644'

- name: add helm apt repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/helm.gpg] {{ helm_apt_repo }} all main"
    state: present
    filename: helm

- name: install helm
  apt:
    name: helm
    state: present
    update_cache: yes
    force_apt_get: yes

# k9s
- name: install k9s binary
  shell: |
    curl -fsSL https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz | tar xz -C /usr/local/bin k9s
  args:
    creates: /usr/local/bin/k9s

...
